version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ETL
    ports:
      - "5432:5432"
  etl_app:
    build: ./ETL
    ports:
      - "8081:8081"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_DOMAIN: postgres
      POSTGRES_DB: ETL
      API: http://api:8080/shift
    depends_on:
      - postgres
  api:
    build: ./Generator
    ports:
    - "8080:8080"

